### ISSUE TITLE
Django 1.6 support gone?

### ISSUE THREAD

**Issue by brycenesbitt** [dmpayton/django-admin-honeypot#23]
This is on Django 1.6:

  File "virtualenvs/xxxxxx/local/lib/python2.7/site-packages/admin_honeypot/migrations/0001_initial.py", line 4, in <module>
    from django.db import models, migrations
ImportError: cannot import name migrations

Version 0.3.0 works on Django 1.6, but no longer seems to be on the python package index.
